<?php
/**
 * @copyright Copyright (c) 2018 www.evincemage.com
 */
?>
<?php if($block->getOrder() && $block->getOrderComment()):?>
<div class="block block-order-details-view">
    <div class="block-content">
        <div class="box box-order-comment">
            <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Order Comment') ?></span></strong>
            <div class="box-content">
               <?php echo $block->getOrderComment();?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>